# syntax=docker/dockerfile:1
ARG IMAGE=public.ecr.aws/sam/build-python3.12

FROM ${IMAGE}
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install \
    poetry==1.8.3 \
    poetry-plugin-export==1.8.0
